<!DOCTYPE html>
<html>
  <head>
    <title>My Hakyll (Heist) Blog - <hakyll field="title"/></title>
    <link rel="stylesheet" type="text/css" href="/css/default.css" />
  </head>
  <body>
    <div id="header">
      <div id="logo">
        <a href="/">My Hakyll Blog</a>
      </div>
      <div id="navigation">
        <a href="/">Home</a>
        <a href="/about.html">About</a>
        <a href="/contact.html">Contact</a>
        <a href="/archive.html">Archive</a>
      </div>
    </div>

    <div id="content">
      <h1><hakyll field="title"/></h1>
      <apply-content/>
    </div>

    <div id="footer">
      Site proudly generated by
      <a href="http://jaspervdj.be/hakyll">Hakyll</a>
    </div>
  </body>
</html>
